module.exports = function interpolateParams (req) {
  // Un-null APIG-proxy-Lambda params in 6+
  let unNulled = [ 'body', 'pathParameters', 'queryStringParameters', 'multiValueQueryStringParameters' ]
  unNulled.forEach(i => {
    if (req[i] === null) req[i] = {}
  })

  // Backfill params generated by <6 VTL
  if (!req.method) req.method = req.httpMethod
  if (!req.params) req.params = req.pathParameters
  if (!req.query)  req.query  = req.queryStringParameters

  // Legacy path parameter interpolation; 6+ gets this for free in `req.path`
  let params = /\{\w+\}/g
  if (params.test(req.path)) {
    let matches = req.path.match(params)
    let vars = matches.map(a => a.replace(/\{|\}/g, ''))
    let idx = 0
    matches.forEach(m => {
      req.path = req.path.replace(m, req.params[vars[idx]])
      idx += 1
    })
  }
  return req
}
